/**
 * FinancialPanel.jsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Full-screen overlay showing renovation NPV / climate-risk financials for
 * all four sites.  Opened from the Toolbar "$ Finance" button.
 *
 * Data: public/financial_data.json  (generated by climate_financial_model.py)
 */

import { useEffect, useState } from 'react'

// ── Helpers ──────────────────────────────────────────────────────────────────

function fmt$k(val) {
  if (val == null || !isFinite(val)) return '—'
  const abs = Math.abs(val)
  if (abs >= 1_000_000) return `$${(val / 1_000_000).toFixed(1)}M`
  if (abs >= 1_000)     return `$${(val / 1_000).toFixed(0)}K`
  return `$${val.toFixed(0)}`
}

function fmtPct(val) {
  if (val == null || !isFinite(val)) return '—'
  return `${val.toFixed(0)}%`
}

const SITE_META = {
  riyadh: { label: 'Riyadh',  climate: 'hot',  flag: '🇸🇦', subtitle: 'Al-Murabba / Diriyah Gate' },
  mecca:  { label: 'Mecca',   climate: 'hot',  flag: '🕌', subtitle: 'Masjid al-Haram surrounds' },
  almaty: { label: 'Almaty',  climate: 'cold', flag: '🇰🇿', subtitle: 'Medeu / Dostyk Embassy Row' },
  astana: { label: 'Astana',  climate: 'cold', flag: '🇰🇿', subtitle: 'Kenesary St / Saryarka Ave / Ishim River' },
}

const SCENARIO_LABELS = {
  A: 'Tree planting',
  B: 'Ground resurfacing',
  C: 'Trees + resurfacing',
  D: 'Shade canopy structure',
}

const SITE_ORDER = ['riyadh', 'mecca', 'almaty', 'astana']

// ── Layer bar ─────────────────────────────────────────────────────────────────
function LayerBar({ label, value, total, color, tooltip }) {
  const pct = total > 0 ? Math.max(2, (value / total) * 100) : 0
  return (
    <div className="fp-layer-row" title={tooltip}>
      <span className="fp-layer-label">{label}</span>
      <div className="fp-layer-track">
        <div className="fp-layer-fill" style={{ width: `${pct}%`, background: color }} />
      </div>
      <span className="fp-layer-val">{fmt$k(value)}</span>
    </div>
  )
}

// ── Per-site card ─────────────────────────────────────────────────────────────
function SiteCard({ siteKey, data }) {
  const meta    = SITE_META[siteKey] ?? { label: siteKey, flag: '', subtitle: '' }
  const isHot   = meta.climate === 'hot'
  const stranded = data?.stranded_rcp45

  if (!data) {
    return (
      <div className="fp-card fp-card-pending">
        <div className="fp-card-head">
          <span className="fp-flag">{meta.flag}</span>
          <div>
            <div className="fp-city">{meta.label}</div>
            <div className="fp-sub">{meta.subtitle}</div>
          </div>
        </div>
        <div className="fp-pending">Financial data not available — run climate_financial_model.py</div>
      </div>
    )
  }

  const {
    capex_usd, scenario_key, floor_area_m2,
    annual_energy_saving_usd, hedonic_uplift_usd, demand_premium_usd, climate_risk_avoided_usd,
    total_value_usd, npv_usd, roi_pct,
    delta_utci_c, projected_utci_2050,
  } = data

  const totalNonEnergy = hedonic_uplift_usd + demand_premium_usd + climate_risk_avoided_usd
  const barTotal = Math.max(total_value_usd, 1)

  // Energy NPV (annuity over 25yr at 8%)
  const energyNpv = annual_energy_saving_usd * (1 - Math.pow(1.08, -25)) / 0.08

  return (
    <div className={`fp-card ${isHot ? 'fp-card-hot' : 'fp-card-cold'}`}>

      {/* Header */}
      <div className="fp-card-head">
        <span className="fp-flag">{meta.flag}</span>
        <div>
          <div className="fp-city">{meta.label}</div>
          <div className="fp-sub">{meta.subtitle}</div>
        </div>
        {stranded && (
          <span className="fp-stranded" title="Stranded asset: projected outdoor thermal conditions (UTCI) exceed 46 °C by 2050 under RCP 4.5 warming. Outdoor spaces become economically unviable — property values face a mandatory discount (up to 25%). Renovation scenarios reduce current UTCI but cannot fully offset the 2050 trajectory.">
            ⚠ Stranded risk
          </span>
        )}
      </div>

      {/* ROI hero */}
      <div className="fp-roi-row">
        <div className="fp-roi-block" title="Return on Investment over the full 25-year analysis horizon: (total value − capex) / capex × 100. Values above 100% mean the renovation pays back more than its cost over its lifetime. Hot-climate sites show higher ROI because climate risk avoided and demand premium layers are larger.">
          <div className="fp-roi-num">{fmtPct(roi_pct)}</div>
          <div className="fp-roi-label">ROI</div>
        </div>
        <div className="fp-roi-block" title="Net Present Value: total discounted value of all benefit layers (energy, hedonic, demand, climate risk) minus the upfront renovation cost (capex). Positive NPV = the project creates value. Discount rate: 8%.">
          <div className="fp-roi-num">{fmt$k(npv_usd)}</div>
          <div className="fp-roi-label">NPV</div>
        </div>
        <div className="fp-roi-block" title="Capital expenditure: upfront cost of the best renovation scenario (materials, labour, installation). Scales with intervention area and type — shade canopies (D) cost more than tree planting (A) or resurfacing (B).">
          <div className="fp-roi-num">{fmt$k(capex_usd)}</div>
          <div className="fp-roi-label">Capex</div>
        </div>
      </div>

      {/* Scenario tag */}
      <div className="fp-scenario-tag">
        Best: Scenario {scenario_key} — {SCENARIO_LABELS[scenario_key] ?? scenario_key}
        &nbsp;·&nbsp;
        <span title="Change in outdoor thermal comfort (Universal Thermal Climate Index) from the best renovation scenario. Positive = warmer (good for cold sites), negative = cooler (good for hot sites). Drives HVAC energy savings and property value uplift.">ΔUTCI {delta_utci_c >= 0 ? '+' : ''}{delta_utci_c?.toFixed(2)} °C</span>
        &nbsp;·&nbsp;
        <span title="Gross Floor Area of adjacent buildings that benefit from the outdoor microclimate improvement. UTCI improvement reduces HVAC loads on perimeter zones of these buildings, generating annual energy savings capitalised into asset value.">{(floor_area_m2 / 1000).toFixed(0)}K m² GFA</span>
      </div>

      {/* Value layers */}
      <div className="fp-layers">
        <div className="fp-layers-title">Value breakdown</div>
        <LayerBar
          label="Energy NPV"
          value={energyNpv}
          total={barTotal}
          color="#4caf50"
          tooltip={`Net present value of annual HVAC energy savings over 25 years (8% discount rate). Each °C of UTCI improvement reduces heating/cooling loads by 2-2.5% on perimeter zones. Annual saving: $${annual_energy_saving_usd.toFixed(0)}/yr.`}
        />
        <LayerBar
          label="Hedonic uplift"
          value={hedonic_uplift_usd}
          total={barTotal}
          color="#2196f3"
          tooltip="Hedonic uplift: property price increase from better outdoor comfort. Based on real estate studies — neighborhoods with higher climate scores command higher $/m² (~$25/m² per 10-point improvement for hot climates, ~$13 for cold)."
        />
        <LayerBar
          label="Demand premium"
          value={demand_premium_usd}
          total={barTotal}
          color="#9c27b0"
          tooltip="Demand premium: capitalised rental yield gain from improved market signals — shorter days-on-market (DOM), higher search velocity, and lower vacancy. Uses default market assumptions (5% cap rate, 3% rental uplift per comfort tier). This layer is often the largest because even modest rental gains capitalise into large asset values at low cap rates. Calibrate with local listing data for accuracy."
        />
        <LayerBar
          label="Climate risk avoided"
          value={climate_risk_avoided_usd}
          total={barTotal}
          color={stranded ? '#f44336' : '#ff9800'}
          tooltip={`Climate risk avoided: asset value preserved by renovating now vs. doing nothing. Under RCP 4.5 warming, outdoor UTCI is projected to reach ${projected_utci_2050} °C by 2050. Properties in locations exceeding 46 °C face mandatory valuation discounts (up to 25%) as outdoor spaces become unusable. This layer measures how much of that future discount is avoided by improving the microclimate today.`}
        />
      </div>

      {/* Climate risk footer */}
      <div className="fp-climate-row">
        <span className="fp-climate-label">2050 UTCI (RCP 4.5)</span>
        <span className={`fp-climate-val ${stranded ? 'fp-stranded-val' : ''}`}>
          {projected_utci_2050} °C
        </span>
      </div>
    </div>
  )
}

// ── Size section header ───────────────────────────────────────────────────────
function SizeHeader({ size, label, sub }) {
  return (
    <div className="fp-size-header">
      <span className="fp-size-pill">{size}</span>
      <div>
        <div className="fp-size-label">{label}</div>
        <div className="fp-size-sub">{sub}</div>
      </div>
    </div>
  )
}

// ── Main panel ────────────────────────────────────────────────────────────────
export default function FinancialPanel({ data, data1km, onClose }) {
  const [activeTab, setActiveTab] = useState('500m')

  // Close on Escape
  useEffect(() => {
    const fn = e => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', fn)
    return () => window.removeEventListener('keydown', fn)
  }, [onClose])

  const has1km = data1km && Object.keys(data1km).length > 0

  return (
    <div className="fp-overlay" onClick={onClose}>
      <div className="fp-panel" onClick={e => e.stopPropagation()}>

        <button className="fp-close" onClick={onClose} title="Close">✕</button>

        <div className="fp-header">
          <div className="fp-title">Renovation Financial Model</div>
          <div className="fp-subtitle">
            Four-layer translation: Physical simulation → Energy savings → Hedonic pricing → Climate risk
          </div>
          <div className="fp-disclaimer">
            All values use literature-based priors — calibrate with local listing data for live deployments.
            Energy layer: base HVAC intensity × UTCI elasticity × floor area × tariff.
            Hedonic prior: $25/m² per 10-pt score improvement (hot), $13 (cold).
            Climate risk: RCP 4.5 CMIP6 delta × 0.7 UTCI sensitivity, capitalised at 8 % discount rate.
          </div>

          {/* Tab switcher */}
          {has1km && (
            <div className="fp-tabs">
              <button
                className={`fp-tab${activeTab === '500m' ? ' fp-tab--active' : ''}`}
                onClick={() => setActiveTab('500m')}
              >
                500 m · Study Area
              </button>
              <button
                className={`fp-tab${activeTab === '1km' ? ' fp-tab--active' : ''}`}
                onClick={() => setActiveTab('1km')}
              >
                1 km · Analysis Zone
              </button>
            </div>
          )}
        </div>

        {/* 500 m section */}
        {(!has1km || activeTab === '500m') && (
          <>
            {has1km && (
              <SizeHeader
                size="500 m"
                label="Study Area — core public space"
                sub="Simulation polygon centred on the intervention site · baseline financial model"
              />
            )}
            <div className="fp-grid">
              {SITE_ORDER.map(k => (
                <SiteCard key={k} siteKey={k} data={data?.[k]} />
              ))}
            </div>
          </>
        )}

        {/* 1 km section */}
        {has1km && activeTab === '1km' && (
          <>
            <SizeHeader
              size="1 km"
              label="Analysis Zone — extended district impact"
              sub="4× floor area · 3.5× capex · same intervention type · district-scale NPV"
            />
            <div className="fp-grid">
              {SITE_ORDER.map(k => (
                <SiteCard key={k} siteKey={k} data={data1km?.[k]} />
              ))}
            </div>
          </>
        )}

      </div>
    </div>
  )
}
