/**
 * FinancialPanel.jsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Full-screen overlay showing renovation NPV / climate-risk financials for
 * all four sites.  Opened from the Toolbar "$ Finance" button.
 *
 * Data: public/financial_data.json  (generated by climate_financial_model.py)
 */

import { useEffect } from 'react'

// ── Helpers ──────────────────────────────────────────────────────────────────

function fmt$k(val) {
  if (val == null || !isFinite(val)) return '—'
  const abs = Math.abs(val)
  if (abs >= 1_000_000) return `$${(val / 1_000_000).toFixed(1)}M`
  if (abs >= 1_000)     return `$${(val / 1_000).toFixed(0)}K`
  return `$${val.toFixed(0)}`
}

function fmtPct(val) {
  if (val == null || !isFinite(val)) return '—'
  return `${val.toFixed(0)}%`
}

const SITE_META = {
  riyadh: { label: 'Riyadh',  climate: 'hot',  flag: '🇸🇦', subtitle: 'Al-Murabba / Diriyah Gate' },
  mecca:  { label: 'Mecca',   climate: 'hot',  flag: '🕌', subtitle: 'Masjid al-Haram surrounds' },
  almaty: { label: 'Almaty',  climate: 'cold', flag: '🇰🇿', subtitle: 'Medeu / Dostyk Embassy Row' },
  astana: { label: 'Astana',  climate: 'cold', flag: '🇰🇿', subtitle: 'Bayterek / Nurzhol Blvd' },
}

const SCENARIO_LABELS = {
  A: 'Tree planting',
  B: 'Ground resurfacing',
  C: 'Trees + resurfacing',
  D: 'Shade canopy structure',
}

const SITE_ORDER = ['riyadh', 'mecca', 'almaty', 'astana']

// ── Layer bar ─────────────────────────────────────────────────────────────────
function LayerBar({ label, value, total, color, tooltip }) {
  const pct = total > 0 ? Math.max(2, (value / total) * 100) : 0
  return (
    <div className="fp-layer-row" title={tooltip}>
      <span className="fp-layer-label">{label}</span>
      <div className="fp-layer-track">
        <div className="fp-layer-fill" style={{ width: `${pct}%`, background: color }} />
      </div>
      <span className="fp-layer-val">{fmt$k(value)}</span>
    </div>
  )
}

// ── Per-site card ─────────────────────────────────────────────────────────────
function SiteCard({ siteKey, data }) {
  const meta    = SITE_META[siteKey] ?? { label: siteKey, flag: '', subtitle: '' }
  const isHot   = meta.climate === 'hot'
  const stranded = data?.stranded_rcp45

  if (!data) {
    return (
      <div className="fp-card fp-card-pending">
        <div className="fp-card-head">
          <span className="fp-flag">{meta.flag}</span>
          <div>
            <div className="fp-city">{meta.label}</div>
            <div className="fp-sub">{meta.subtitle}</div>
          </div>
        </div>
        <div className="fp-pending">Financial data not available — run climate_financial_model.py</div>
      </div>
    )
  }

  const {
    capex_usd, scenario_key, floor_area_m2,
    annual_energy_saving_usd, hedonic_uplift_usd, demand_premium_usd, climate_risk_avoided_usd,
    total_value_usd, npv_usd, roi_pct,
    delta_utci_c, projected_utci_2050,
  } = data

  const totalNonEnergy = hedonic_uplift_usd + demand_premium_usd + climate_risk_avoided_usd
  const barTotal = Math.max(total_value_usd, 1)

  // Energy NPV (annuity over 25yr at 8%)
  const energyNpv = annual_energy_saving_usd * (1 - Math.pow(1.08, -25)) / 0.08

  return (
    <div className={`fp-card ${isHot ? 'fp-card-hot' : 'fp-card-cold'}`}>

      {/* Header */}
      <div className="fp-card-head">
        <span className="fp-flag">{meta.flag}</span>
        <div>
          <div className="fp-city">{meta.label}</div>
          <div className="fp-sub">{meta.subtitle}</div>
        </div>
        {stranded && (
          <span className="fp-stranded" title="Site projected to exceed 46°C UTCI by 2050 under RCP 4.5">
            ⚠ Stranded risk
          </span>
        )}
      </div>

      {/* ROI hero */}
      <div className="fp-roi-row">
        <div className="fp-roi-block">
          <div className="fp-roi-num">{fmtPct(roi_pct)}</div>
          <div className="fp-roi-label">ROI</div>
        </div>
        <div className="fp-roi-block">
          <div className="fp-roi-num">{fmt$k(npv_usd)}</div>
          <div className="fp-roi-label">NPV</div>
        </div>
        <div className="fp-roi-block">
          <div className="fp-roi-num">{fmt$k(capex_usd)}</div>
          <div className="fp-roi-label">Capex</div>
        </div>
      </div>

      {/* Scenario tag */}
      <div className="fp-scenario-tag">
        Best: Scenario {scenario_key} — {SCENARIO_LABELS[scenario_key] ?? scenario_key}
        &nbsp;·&nbsp;
        ΔUTCI {delta_utci_c >= 0 ? '+' : ''}{delta_utci_c?.toFixed(2)} °C
        &nbsp;·&nbsp;
        {(floor_area_m2 / 1000).toFixed(0)}K m² GFA
      </div>

      {/* Value layers */}
      <div className="fp-layers">
        <div className="fp-layers-title">Value breakdown</div>
        <LayerBar
          label="Energy NPV"
          value={energyNpv}
          total={barTotal}
          color="#4caf50"
          tooltip={`$${annual_energy_saving_usd.toFixed(0)}/yr utility saving · base intensity × UTCI elasticity`}
        />
        <LayerBar
          label="Hedonic uplift"
          value={hedonic_uplift_usd}
          total={barTotal}
          color="#2196f3"
          tooltip="Property price premium from comfort-score improvement (literature prior)"
        />
        <LayerBar
          label="Demand premium"
          value={demand_premium_usd}
          total={barTotal}
          color="#9c27b0"
          tooltip="Capitalised rental yield gain from improved demand signals (DOM, search velocity)"
        />
        <LayerBar
          label="Climate risk avoided"
          value={climate_risk_avoided_usd}
          total={barTotal}
          color={stranded ? '#f44336' : '#ff9800'}
          tooltip={`Asset value preserved vs. unmitigated stranded-risk discount under RCP 4.5 (UTCI 2050: ${projected_utci_2050} °C)`}
        />
      </div>

      {/* Climate risk footer */}
      <div className="fp-climate-row">
        <span className="fp-climate-label">2050 UTCI (RCP 4.5)</span>
        <span className={`fp-climate-val ${stranded ? 'fp-stranded-val' : ''}`}>
          {projected_utci_2050} °C
        </span>
      </div>
    </div>
  )
}

// ── Main panel ────────────────────────────────────────────────────────────────
export default function FinancialPanel({ data, onClose }) {
  // Close on Escape
  useEffect(() => {
    const fn = e => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', fn)
    return () => window.removeEventListener('keydown', fn)
  }, [onClose])

  return (
    <div className="fp-overlay" onClick={onClose}>
      <div className="fp-panel" onClick={e => e.stopPropagation()}>

        <button className="fp-close" onClick={onClose} title="Close">✕</button>

        <div className="fp-header">
          <div className="fp-title">Renovation Financial Model</div>
          <div className="fp-subtitle">
            Four-layer translation: Physical simulation → Energy savings → Hedonic pricing → Climate risk
          </div>
          <div className="fp-disclaimer">
            All values use literature-based priors — calibrate with local listing data for live deployments.
            Energy layer: base HVAC intensity × UTCI elasticity × floor area × tariff.
            Hedonic prior: $25/m² per 10-pt score improvement (hot), $13 (cold).
            Climate risk: RCP 4.5 CMIP6 delta × 0.7 UTCI sensitivity, capitalised at 8 % discount rate.
          </div>
        </div>

        <div className="fp-grid">
          {SITE_ORDER.map(k => (
            <SiteCard key={k} siteKey={k} data={data?.[k]} />
          ))}
        </div>

      </div>
    </div>
  )
}
